# Generated by Django 4.2.7 on 2023-11-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerproduct',
            old_name='reply_to',
            new_name='parent',
        ),
    ]
