# Generated by Django 4.2.7 on 2023-11-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='answerproduct',
            name='relation_choose',
            field=models.CharField(blank=True, choices=[('like', 'می پسندم'), ('dislike', 'نمی پسندم')], default=None, max_length=7, verbose_name='واکنش کاربر'),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='relation_choose',
            field=models.CharField(blank=True, choices=[('like', 'می پسندم'), ('dislike', 'نمی پسندم')], default=None, max_length=7, verbose_name='واکنش کاربر'),
        ),
    ]
