# Generated by Django 4.2.7 on 2023-11-16 19:32

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='update_information',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 11, 16, 19, 32, 7, 400536, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ اخرین ورود'),
        ),
    ]
