# Generated by Django 4.2.7 on 2023-11-27 21:37

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.AlterModelOptions(
            name='jobusermodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='jobusermodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobusermodel',
            name='job',
            field=models.CharField(choices=[('IT', 'It'), ('financial accounting', 'Financial Accounting'), ('sale marketing', 'Sale Marketing'), ('health medical', 'Health Medicine'), ('education training', 'Education Training'), ('engineer construction', 'Engineer Constraction'), ('art design', 'Art Design'), ('restaurant food services', 'Restaurent Food Services'), ('commercial legal', 'Commercial Legal'), ('environment sustainability', 'Environment Sustainablity')], default=None, max_length=26),
        ),
        migrations.AlterField(
            model_name='jobusermodel',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified_mmobile_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 11, 27, 21, 37, 2, 950753, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nation_code',
            field=models.CharField(blank=True, help_text='max length 10 characters', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
    ]
