# Generated by Django 4.2.7 on 2023-11-20 10:08

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobusermodel',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 11, 20, 10, 8, 14, 839051, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ اخرین ورود'),
        ),
    ]
