# Generated by Django 4.2.7 on 2023-11-20 10:37

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_update_at_jobusermodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recycleuser',
            options={'verbose_name': 'کاربر پاک شده', 'verbose_name_plural': 'کاربران پاک شده'},
        ),
        migrations.AlterField(
            model_name='jobusermodel',
            name='job',
            field=models.CharField(choices=[('Sportman', 'Sportman'), ('Historiology', 'Historiology'), ('Social Sciences', 'SocialـSciences'), ('Reporter', 'Reporter'), ('Lawyer', 'Lawyer'), ('Engineering', 'Engineering'), ('Graphics', 'Graphics'), ('Marketing', 'Marketing'), ('Transportation', 'Transportation'), ('Programming', 'Programming'), ('Sales & Marketing', 'Sales Marketing')], default=None, max_length=17, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 11, 20, 10, 37, 0, 521998, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ اخرین ورود'),
        ),
    ]
