# Generated by Django 4.2.7 on 2023-12-01 00:06

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 12, 1, 0, 6, 39, 51855, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
