# Generated by Django 4.2.7 on 2023-11-20 11:05

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_recycleuser_options_alter_jobusermodel_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobusermodel',
            name='job',
            field=models.CharField(choices=[('IT', 'فناوری و اطلاعات'), ('financial accounting', 'مالی و حسابداری'), ('sale marketing', 'مالی و حسابداری'), ('health medical', 'سلامت و پزشکی'), ('education training', 'فروش و بازاریابی'), ('engineer construction', 'آموزش و تربیت'), ('art design', 'مهندسی و ساخت'), ('restaurant food services', 'خدمات رستورانی و غذایی'), ('commercial legal', 'بازرگانی و حقوق'), ('environment sustainability', 'محیط زیست و پایداری')], default=None, max_length=26, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'زن'), ('male', 'مرد')], default='male', max_length=6, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 11, 20, 11, 5, 2, 662450, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ اخرین ورود'),
        ),
    ]
