# Generated by Django 4.2.7 on 2023-11-21 13:58

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nation_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 11, 21, 13, 58, 9, 158249, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ اخرین ورود'),
        ),
    ]
