# Generated by Django 4.2.7 on 2023-11-21 14:02

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_nation_code_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 11, 21, 14, 2, 26, 189054, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ اخرین ورود'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nation_code',
            field=models.CharField(blank=True, help_text='max length 10 characters', max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
    ]
