# Generated by Django 4.2.7 on 2023-11-21 14:33

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_last_login_alter_user_nation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 11, 21, 14, 33, 22, 6464, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ اخرین ورود'),
        ),
    ]
