# Generated by Django 4.2.7 on 2023-11-11 14:27

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 11, 11, 14, 27, 25, 78128, tzinfo=datetime.timezone.utc), null=True, verbose_name='date joined'),
        ),
    ]
