# Generated by Django 4.2.7 on 2023-11-14 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_imagesmodel_create_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionValueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='عنوان')),
                ('body_option_value', models.CharField(max_length=100, verbose_name='متن عنوان')),
            ],
            options={
                'verbose_name': 'option value',
                'verbose_name_plural': 'option values',
                'db_table': 'option_value',
            },
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ManyToManyField(related_name='product_images', to='images.imagesmodel'),
        ),
        migrations.AddField(
            model_name='sallermodel',
            name='performance_product',
            field=models.CharField(choices=[('very bad', 'very bad'), ('bad', 'bad'), ('normall', 'normall'), ('best', 'best'), ('very best', 'very best')], default='very best', max_length=9, verbose_name='عملکرد کالا'),
        ),
        migrations.AlterField(
            model_name='option',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='توسط کاربر ایجاد شده'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='barcode',
            field=models.PositiveBigIntegerField(verbose_name='بارکد کالا'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='توسط کاربر ایجاد شده'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='title_products', to='products.sallermodel'),
        ),
        migrations.AlterField(
            model_name='sallermodel',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='توسط کاربر ایجاد شده'),
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table='product',
        ),
    ]
