# Generated by Django 4.2.7 on 2023-12-03 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='productline',
            name='product_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='product_types', to='products.producttype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductTypeAttrbute',
        ),
    ]
