# Generated by Django 4.2.7 on 2023-11-20 10:08

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sallermodel',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
