# Generated by Django 4.2.7 on 2023-11-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlinemodel',
            name='product_line',
        ),
    ]
