# Generated by Django 4.2.7 on 2023-11-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevaluemodel',
            name='attribute',
        ),
    ]
