# Generated by Django 4.2.7 on 2023-11-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlinemodel',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productlinemodel',
            name='description',
            field=models.TextField(blank=True, help_text='explain description product', null=True),
        ),
    ]
