# Generated by Django 4.2.7 on 2023-11-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sallers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='saller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sallers', to='sallers.genuinsaller'),
            preserve_default=False,
        ),
    ]
