# Generated by Django 4.2.7 on 2023-11-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_imagesmodel_alter_image_imagesmodel_height_image_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='عنوان ویژگی')),
            ],
            options={
                'verbose_name': 'product attribute',
                'verbose_name_plural': 'product attrobutes',
                'db_table': 'product_attribute',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'product attribute value',
                'verbose_name_plural': 'product attribute values',
                'db_table': 'product_attribute_value',
            },
        ),
        migrations.DeleteModel(
            name='OptionValueModel',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='option',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='company_warrent_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام شرکت گارانتی کننده'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='barcode',
            field=models.PositiveBigIntegerField(blank=True, verbose_name='بارکد کالا'),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='saller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sallers', to='products.sallermodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='images.imagesmodel'),
            preserve_default=False,
        ),
    ]
