# Generated by Django 4.2.7 on 2023-12-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_attribute_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='product_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_value_product_line', to='products.productline'),
            preserve_default=False,
        ),
    ]
