# Generated by Django 4.2.7 on 2023-11-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productlinemodel_is_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevaluemodel',
            name='value_char',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattributemodel',
            name='types',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('float', 'Float'), ('datetime', 'Dateetime'), ('date', 'Date'), ('charfield', 'Charfield'), ('option', 'Option'), ('multi_option', 'Multi Option')], default='text', max_length=12),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
