# Generated by Django 4.2.7 on 2023-12-03 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_product_line_productline_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productline',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_line',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='product_lines', to='products.productline'),
            preserve_default=False,
        ),
    ]
