# Generated by Django 4.2.7 on 2023-12-03 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_product_type_productline_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='product_product_type', to='products.producttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productline',
            name='product_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_types', to='products.producttype'),
        ),
    ]
