# Generated by Django 4.2.7 on 2023-11-22 07:46

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productline_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
