# Generated by Django 4.2.7 on 2023-11-25 07:41

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productlinemodel_product_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی')),
                ('brand_name', models.CharField(max_length=100, unique=True, verbose_name='نام برند')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'db_table': 'brand',
            },
        ),
        migrations.AlterModelOptions(
            name='productlineattributevaluemodel',
            options={'verbose_name': 'product line attribute value', 'verbose_name_plural': 'product line attribute values'},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='company_warrent_name',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='warrenty_choose',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='products.brandmodel'),
            preserve_default=False,
        ),
    ]
