# Generated by Django 4.2.7 on 2023-11-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_saller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
    ]
