# Generated by Django 4.2.7 on 2023-11-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattributevaluemodel_value_char_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevaluemodel',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevaluemodel',
            name='value_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevaluemodel',
            name='value_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevaluemodel',
            name='value_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevaluemodel',
            name='value_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
