# Generated by Django 4.2.7 on 2023-11-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_imagesmodel_file_hash_imagesmodel_file_size_and_more'),
        ('products', '0003_alter_productmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='images.imagesmodel'),
        ),
    ]
