# Generated by Django 4.2.7 on 2023-12-03 07:53

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productline_attribute_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='attribute',
        ),
        migrations.CreateModel(
            name='ProductAttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_attribute_type_attributes', to='products.attribute')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_attribute_product_type', to='products.producttype')),
            ],
            options={
                'unique_together': {('attribute', 'product_type')},
            },
        ),
        migrations.AddField(
            model_name='producttype',
            name='attribute',
            field=models.ManyToManyField(related_name='product_type_attribute', to='products.productattributetype'),
        ),
    ]
