# Generated by Django 4.2.7 on 2023-11-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productattributevaluemodel_value_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
