# Generated by Django 4.2.7 on 2023-11-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productattributemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlinemodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productmodel'),
            preserve_default=False,
        ),
    ]
