# Generated by Django 4.2.7 on 2023-11-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_imagesmodel_file_hash_and_more'),
        ('products', '0004_alter_productmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='images.imagesmodel'),
        ),
    ]
