# Generated by Django 4.2.7 on 2023-12-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_producttype_attribute_productattributetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeType',
        ),
    ]
