# Generated by Django 4.2.7 on 2023-11-30 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_remove_brandmodel_product'),
        ('products', '0005_productattributemodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_brand', to='Category.category'),
            preserve_default=False,
        ),
    ]
