# Generated by Django 4.2.7 on 2023-11-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productlinemodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevaluemodel',
            name='attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.productattributemodel'),
            preserve_default=False,
        ),
    ]
