# Generated by Django 4.2.7 on 2023-12-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_producttype_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='produt_type_title',
        ),
    ]
