# Generated by Django 4.2.7 on 2023-11-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productattributevaluemodel_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlineattributevaluemodel',
            old_name='attr_value',
            new_name='attr_values',
        ),
        migrations.AlterUniqueTogether(
            name='productlineattributevaluemodel',
            unique_together={('attr_values', 'product_line')},
        ),
    ]
