# Generated by Django 4.2.7 on 2023-11-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0008_brandmodel_created_at_brandmodel_updated_at'),
        ('products', '0006_productmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_brand', to='Category.brandmodel'),
        ),
    ]
