# Generated by Django 4.2.7 on 2023-11-30 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productmodel_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlinemodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productlinemodel',
            name='require_shipping',
        ),
        migrations.RemoveField(
            model_name='productlinemodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productlinemodel',
            name='title_productLine',
        ),
        migrations.AddField(
            model_name='productlinemodel',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlinemodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='line_products', to='products.productmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlinemodel',
            name='sku',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productlinemodel',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
