# Generated by Django 4.2.7 on 2023-12-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_attributevalue_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='types',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('float', 'Float'), ('datetime', 'Datetime'), ('date', 'Date'), ('charfield', 'Charfield'), ('option', 'Option'), ('multi_option', 'Multi Option')], default='text', max_length=12, unique=True),
        ),
    ]
