# Generated by Django 4.2.7 on 2023-11-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productmodel_product_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlinemodel',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_lines', to='products.productmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='structure',
            field=models.CharField(choices=[('standalone', 'Standalone'), ('parent', 'Parent'), ('child', 'Child')], default='standalone', max_length=12),
        ),
    ]
