# Generated by Django 4.2.7 on 2023-12-03 10:02

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_producttype_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('is_publish', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'option',
            },
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('is_publish', models.BooleanField(default=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='option_group_options', to='products.option')),
            ],
            options={
                'db_table': 'option_group',
            },
        ),
    ]
