# Generated by Django 4.2.7 on 2023-11-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlinemodel',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
