# Generated by Django 4.2.7 on 2023-11-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productlinemodel_is_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattributemodel',
            old_name='is_active',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='productlinemodel',
            old_name='is_publish',
            new_name='is_public',
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productattributevaluemodel',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
