# Generated by Django 4.2.7 on 2023-11-30 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_is_active_productattributemodel_is_public_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optiongroup',
            old_name='is_public',
            new_name='is_publish',
        ),
        migrations.RenameField(
            model_name='productattributemodel',
            old_name='is_public',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='productattributevaluemodel',
            old_name='is_public',
            new_name='is_publish',
        ),
        migrations.RenameField(
            model_name='productlinemodel',
            old_name='is_public',
            new_name='is_publish',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='is_public',
            new_name='is_publish',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='productattributemodel',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productlinemodel',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_products', to='products.productmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
