# Generated by Django 4.2.7 on 2023-11-30 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_is_public_optiongroup_is_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlinemodel',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_lines', to='products.productmodel'),
        ),
    ]
