# Generated by Django 4.2.7 on 2023-12-01 00:06

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_is_active_imagesmodel_is_publish'),
        ('products', '0017_alter_productmodel_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='images.imagesmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_image', to='products.productmodel')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ManyToManyField(to='products.productimage'),
        ),
    ]
