# Generated by Django 4.2.7 on 2023-12-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productimage_productmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_line',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='products_image', to='products.productlinemodel'),
            preserve_default=False,
        ),
    ]
