# Generated by Django 4.2.7 on 2023-12-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_image_line', to='products.productlinemodel'),
        ),
    ]
