# Generated by Django 4.2.7 on 2023-11-30 06:45

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('brand_name', models.CharField(db_index=True, max_length=50)),
                ('is_publish', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
    ]
