# Generated by Django 4.2.7 on 2023-11-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productattributemodel_is_active'),
        ('Category', '0002_brandmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='product_brands', to='products.productmodel'),
            preserve_default=False,
        ),
    ]
