# Generated by Django 4.2.7 on 2023-11-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_brandmodel_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodel',
            name='product',
        ),
    ]
