# Generated by Django 4.2.7 on 2023-11-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_remove_brandmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
