# Generated by Django 4.2.7 on 2023-11-30 07:46

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0007_remove_brandmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
    ]
