# Generated by Django 4.2.7 on 2023-11-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productmodel_image'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesmodel',
            name='product_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='products.productmodel'),
            preserve_default=False,
        ),
    ]
