# Generated by Django 4.2.7 on 2023-12-01 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesmodel',
            old_name='is_active',
            new_name='is_publish',
        ),
    ]
