# Generated by Django 4.2.7 on 2023-11-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesmodel',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
