# Generated by Django 4.2.7 on 2023-11-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_update_at_imagesmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesmodel',
            name='file_hash',
            field=models.CharField(db_index=True, default=0, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='file_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='focal_point_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='focal_point_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='focal_point_x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='focal_point_y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagesmodel',
            name='alter_image',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیح در مورد عکس'),
        ),
        migrations.AlterField(
            model_name='imagesmodel',
            name='height_image',
            field=models.SmallIntegerField(editable=False, verbose_name='ارتفاع'),
        ),
        migrations.AlterField(
            model_name='imagesmodel',
            name='image',
            field=models.ImageField(height_field='height_image', upload_to='images/%Y/%m/%d/', verbose_name='عکس', width_field='width_image'),
        ),
        migrations.AlterField(
            model_name='imagesmodel',
            name='width_image',
            field=models.SmallIntegerField(editable=False, verbose_name='عرض'),
        ),
    ]
