# Generated by Django 4.2.7 on 2023-11-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productmodel_image'),
        ('images', '0002_imagesmodel_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesmodel',
            name='product_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='products.productmodel'),
        ),
    ]
