# Generated by Django 4.2.7 on 2023-11-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_imagesmodel_file_hash_imagesmodel_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesmodel',
            name='file_hash',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='imagesmodel',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
