# Generated by Django 4.2.7 on 2023-11-29 18:40

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenuinSaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('nation_code', models.CharField(help_text='max length 10 characters', max_length=10, verbose_name='کد ملی')),
                ('card_number', models.CharField(blank=True, help_text='0000-0000-0000-0000', max_length=16, null=True, unique=True, verbose_name='شماره کارت بانکی')),
                ('sheba_number', models.CharField(blank=True, help_text='IR-000000000000000000000000', max_length=24, null=True, unique=True, verbose_name='شماره شبای  بانکی')),
                ('shop_name', models.CharField(db_index=True, help_text='excample azarakhs, ...', max_length=50, unique=True, verbose_name='نام فروشگاه')),
            ],
            options={
                'verbose_name': 'genuis saller',
                'verbose_name_plural': 'genuis sellers',
                'db_table': 'genuin_saller',
            },
        ),
        migrations.CreateModel(
            name='legalSaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(max_length=50, verbose_name='نام شرکت')),
                ('nation_code_company', models.CharField(max_length=11, verbose_name='کد ملی شرکت')),
                ('economy_code_company', models.CharField(max_length=12, verbose_name='کد اقتصادی شرکت')),
                ('sheba_number', models.CharField(help_text='IR-000000000000000000000000', max_length=24, unique=True, verbose_name='شماره شبای  بانکی')),
            ],
            options={
                'verbose_name': 'legal saller',
                'verbose_name_plural': 'legal sellers',
                'db_table': 'legal_saller',
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('state', models.CharField(max_length=100, verbose_name='شهرستان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('location', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('plaque', models.CharField(blank=True, max_length=11, null=True, verbose_name='پلاک')),
                ('postacl_code', models.CharField(max_length=11, verbose_name='کد پستی')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Multiplehoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='متن سوال')),
            ],
            options={
                'verbose_name': 'multiple option',
                'verbose_name_plural': 'multiple options',
                'db_table': 'multiple_option',
            },
        ),
        migrations.CreateModel(
            name='SignatoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='امضا کننده مالک شرکت')),
                ('company_owner_signatory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatories', to='sallers.legalsaller')),
            ],
            options={
                'verbose_name': 'signatory',
                'verbose_name_plural': 'signatories',
                'db_table': 'signatories',
            },
        ),
        migrations.CreateModel(
            name='MultipleChooseAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_option', models.CharField(blank=True, max_length=50, null=True, verbose_name='گزینه سوال')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_question', to='sallers.multiplehoose')),
            ],
            options={
                'verbose_name': 'multiple choose',
                'verbose_name_plural': 'multiple choiceses',
                'db_table': 'multiple_choose_atrribute',
            },
        ),
    ]
