# Generated by Django 4.2.7 on 2023-11-10 16:04

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=100, verbose_name='english name')),
                ('fa_name', models.CharField(max_length=100, verbose_name='fa name')),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('create_product', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='create product')),
                ('update_product', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='update product')),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('is_public', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('in_stock', models.PositiveSmallIntegerField(verbose_name='موجودی انبار')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
    ]
