# Generated by Django 4.2.7 on 2023-11-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_title', models.CharField(max_length=50, verbose_name='عنوان ويژگی')),
                ('attr_choose', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('float', 'Float')], default='text', max_length=7)),
                ('title_attr', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('track_stock', models.BooleanField(default=True)),
                ('require_shipping', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'product class',
                'verbose_name_plural': 'product classes',
            },
        ),
    ]
