# Generated by Django 4.2.7 on 2023-11-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='product_parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_attr', to='products.productmodel'),
            preserve_default=False,
        ),
    ]
