# Generated by Django 4.2.7 on 2023-11-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_optiongroup_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='attr_text',
            field=models.CharField(default=0, max_length=50, verbose_name='متن ویژگی'),
            preserve_default=False,
        ),
    ]
